server.port=3000
server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${USERS_URL_DATABASE}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.url=/swagger.yaml
springdoc.swagger-ui.path=/swagger

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.stmp.auth=true
spring.mail.properties.mail.starttls.enable=true

spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

spring.main.allow-circular-references=true

jwt.secret=${JWT_SECRET}

azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=assets