spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      routes:
        - id: teams
          uri: http://localhost:3000
          predicates:
            - Path=/teams/**
        - id: codes
          uri: http://localhost:3000
          predicates:
            - Path=/codes/**
        - id: users
          uri: http://localhost:3000
          predicates:
            - Path=/users/**
        - id: injuries
          uri: http://localhost:3000
          predicates:
            - Path=/injuries/**
        - id: athlete-descs
          uri: http://localhost:3000
          predicates:
            - Path=/athlete-descs/**
        - id: athletes
          uri: http://localhost:3000
          predicates:
            - Path=/athletes/**
        - id: athlete-historics
          uri: http://localhost:3000
          predicates:
            - Path=/athlete-historics/**
        - id: coaches
          uri: http://localhost:3000
          predicates:
            - Path=/coaches/**
        - id: games
          uri: http://localhost:3002
          predicates:
            - Path=/games/**
        - id: trainings
          uri: http://localhost:3002
          predicates:
            - Path=/trainings/**
        - id: game-results
          uri: http://localhost:3002
          predicates:
            - Path=/game-results/**
        - id: graphs
          uri: http://localhost:3002
          predicates:
            - Path=/graphs/**
        - id: blob-storage
          uri: http://localhost:3000
          predicates:
            - Path=/blob-storage/**